### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by andrascsibi** [vuejs/vueify-example#10]
Any chance of providing an example unit test with karma/jasmine as recommended in the "Building Large Scale Apps" documentation?

Thanks,
Andras

BTW, Vue is an amazing library. Reactive data binding using getters/setters wrapping is such a beautiful idea and so simple, I wonder why anyone is bothering with virtual DOM diffing&patching anymore.

**Comment by matisoffn** [comment]
+1

**Comment by BYODKM** [comment]
+1

**Comment by pedrofgsrj** [comment]
+1

**Comment by natetheaverage** [comment]
+1

**Comment by AnsonHwang86** [comment]
+1

**Comment by yyx990803** [comment]
There is example for unit tests now.
