### ISSUE TITLE
server port not 8080 but 3123

### ISSUE THREAD

**Issue by ramstein74** [vuejs/vueify-example#11]
hi, when i start npm run dev i see 
[HMR] Listening on localhost:3123

however you say in the docs that the server starts at port 8080

2nd
browsing to localhost:3123 i get the error
Cannot GET

thank you

**Comment by yyx990803** [comment]
That is the internal port for pushing/listening for hot module updates, not the port you should use for accessing the app.

**Comment by ramstein74** [comment]
why do i get 

Cannot GET on port 3123 ?

**Comment by yyx990803** [comment]
Because you should not be accessing that port... It's used by the tools
only and they probably use POST.

**Comment by ramstein74** [comment]
Now i dont get it.
How do i try vueify example in the browser?
Em 06/11/2015 19:00, "Evan You" <notifications@github.com> escreveu:

> Because you should not be accessing that port... It's used by the tools
> only and they probably use POST.

**Comment by yyx990803** [comment]
As the doc says, use port 8080.

**Comment by ramstein74** [comment]
That is what i´m trying to tell you.
It does not work on port 8080 neither on the other port.
I´m on windows. Can you help ?

[image: Imagem inline 1]

2015-11-06 20:07 GMT+00:00 Evan You <notifications@github.com>:

**Comment by yyx990803** [comment]
Looks like Windows npm script doesn't like `&` so it's not running the npm `dev` script after it. In fact all you need is some local http server to serve the folder.
