### ISSUE TITLE
Use vue-router at the same time, but browserify cannot transform all the *.vue files.

### ISSUE THREAD

**Issue by DanielZhu** [vuejs/vueify-example#4]
I'm using Vuejs + vue-router + vueify + browserify + gulp to build up the website
But the task cannot include the real *.vue files. 

eg:
If I try to include the 404 page like this ``` var viewNotFound = require('./views/404.vue')```
As a result, I cannot found any content from 404.vue in the bundle.js . Also the app.vue file is missing, too.

```
var Vue = require("vue");
var VueRouter = require("vue-router");
var appView = require('./app.vue');
var view404 = require("./views/404.vue");

Vue.use(VueRouter);

var App = Vue.extend(appView);
router.map({
    '*': {
        component: view404
    },
    '/': {
        component: homeView
    }
})
// Start the App
router.start(App, '#app');
```
Does anybody know what's wrong with the code stuffs?

**Comment by yyx990803** [comment]
There's likely a problem in your setup - .e.g not using the `vueify` transform when in the browserify task. But since you are using gulp, it's not related to this repo, and I can't help you without more info.
